# version: "3"

services:
  # PHP & Apache service
  web:
    image: php:8.1-apache
    container_name: event-analytics-web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
    environment:
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT}
      - APP_ENV=${APP_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    command: >
      bash -c "a2enmod rewrite &&
               docker-php-ext-install pdo pdo_mysql &&
               apache2-foreground"

  # MySQL service
  db:
    image: mysql:8.0
    container_name: event-analytics-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  # phpMyAdmin (optional but helpful)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: event-analytics-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

volumes:
  mysql_data:
